//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_Construccion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int IdUser { get; set; }
        public string NombreUsuario { get; set; }
        public string Contraseña { get; set; }
        public string NombrePila { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime Fecha_nacimiento { get; set; }
        public string Genero { get; set; }
        public string Correo { get; set; }
    }
}
